### ISSUE TITLE
I've been trying to set up this example but can't seem to put up a server

### ISSUE THREAD

**Issue by kszpirak** [FusionAuth/fusionauth-nodejs-react-example#7]
Here is the error log, any idea what may be going wrong here?

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.13.4
3 info using node@v13.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle fusionauth-nodejs-react-example@1.0.0~prestart: fusionauth-nodejs-react-example@1.0.0
6 info lifecycle fusionauth-nodejs-react-example@1.0.0~start: fusionauth-nodejs-react-example@1.0.0
7 verbose lifecycle fusionauth-nodejs-react-example@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle fusionauth-nodejs-react-example@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/kszpirak/src/fusionauth-nodejs-react-example/server/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
9 verbose lifecycle fusionauth-nodejs-react-example@1.0.0~start: CWD: /Users/kszpirak/src/fusionauth-nodejs-react-example/server
10 silly lifecycle fusionauth-nodejs-react-example@1.0.0~start: Args: [ '-c', 'node server.js' ]
11 silly lifecycle fusionauth-nodejs-react-example@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle fusionauth-nodejs-react-example@1.0.0~start: Failed to exec start script
13 verbose stack Error: fusionauth-nodejs-react-example@1.0.0 start: `node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:305:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:305:20)
13 verbose stack     at maybeClose (internal/child_process.js:1028:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid fusionauth-nodejs-react-example@1.0.0
15 verbose cwd /Users/kszpirak/src/fusionauth-nodejs-react-example/server
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v13.5.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error fusionauth-nodejs-react-example@1.0.0 start: `node server.js`
22 error Exit status 1
23 error Failed at the fusionauth-nodejs-react-example@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by lmeerwood** [comment]
I, too, am having the same issue. I can't even see what's causing the crash on my machine.
